syntax = "proto3";

package proto.service.datanode;

option cc_generic_services = true;

import "common.proto";
import "error_code.proto";

message WriteAtRequest {
    proto.common.RequestCommon request_common = 1;
    uint64 extent_id = 2;
    uint64 session_id = 3;
    uint32 shard_id = 4;
    bytes  data = 5;
    uint32 offset = 6;
}

message WriteAtResponse {
    proto.common.ErrorCode error_code = 1;
    // TODO: black list
}

message ReadAtRequest {
    proto.common.RequestCommon request_common = 1;
    uint64 extent_id = 2;
    uint32 shard_id = 3;
    uint32 offset = 4;
    uint32 length = 5;
}

message ReadAtResponse {
    proto.common.ErrorCode error_code = 1;
    bytes data = 2;
    // TODO: black list
}