syntax = "proto3";

package proto.common;

enum ErrorCode {
    PANCAKE_STORE_OK = 0;
    PANCAKE_STORE_CLUSTER_ID_NOT_MATCH = 1;
    PANCAKE_STORE_YAML_CONFIG_INVALID = 2;
    PANCAKE_STORE_CONFIG_INVALID = 3;

    // datanode error code 1xxxx

    // datanode service error codes
    DATANODE_SERVICE_DEVICE_ALREADY_EXISTS = 10001;
    DATANODE_SERVICE_DATANODE_ID_NOT_MATCH = 10002;
    DATANODE_SERVICE_REQUEST_ARGUMENT_INVALID = 10003;

    // datanode device error codes
    DATANODE_DEVICE_READ_LINK_FAILED = 11001;

    // master error code

    // rpc caller error code 3xxxx
    RPC_CALLER_INVOKE_FAILED = 30001;
    RPC_CALLER_RESPONSE_PARSE_FAILED = 30002;
};